# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "county-two"
client_id = "7a8ef865d2089bdc75c158247d9625ad"
application_url = "https://appear-sigma-capitol-purple.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://appear-sigma-capitol-purple.trycloudflare.com/auth/callback",
  "https://appear-sigma-capitol-purple.trycloudflare.com/auth/shopify/callback",
  "https://appear-sigma-capitol-purple.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "county-easytek.myshopify.com"
